import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Automatically generate sidebar from filesystem structure
  tutorialSidebar: [
    {
      type: "autogenerated",
      dirName: ".", // Generate sidebar from the docs root directory
    },
  ],
};

export default sidebars;
